on: [issue_comment, pull_request_review]

jobs:
  toxic_check:
    runs-on: ubuntu-latest
    name: action getenv
    steps:
      - uses: actions/checkout@v2
      - name: getenv - action step
        uses: Akshay090/getenv@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
